name: Build Swift Latest

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-latest:
    strategy:
      fail-fast: false
      matrix:
        swift-target-arch: ["armv7"]
        distribution: ["debian-bookworm"]
        include:
          - swift-target-arch: "armv6"
            distribution: "raspios-bookworm"
    env:
      SWIFT_VERSION: "5.9.2"
      SWIFT_TAG: swift-5.9.2-RELEASE
    name: Build Swift
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/checkout-swift
      name: Fetch Swift ${{ env.SWIFT_TAG }}
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-workspace-cache: swift-workspace
    - name: Generate Builder Container
      shell: bash
      run: ./swift-builder/build-container.sh
    - uses: ./.github/actions/build-for-distribution
      name: Build & Publish Swift ${{ env.SWIFT_VERSION }}
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-target-arch: ${{ matrix.swift-target-arch }}
        distribution: ${{ matrix.distribution }}
        builder-tag: ${{ env.SWIFT_VERSION }}
